include_guard()
if(DOOBIUS_CHECK_PKG_MANAGER)
    set(VCPKG_MANIFEST_FEATURES "package-manager-test")
else()
    set(VCPKG_MANIFEST_FEATURES "framework")
    if(DOOBIUS_BUILD_TESTS)
        list(APPEND VCPKG_MANIFEST_FEATURES "test")
    endif()
endif()