function(_get_topo_sort_with_deps OUT_VAR INITIAL_REQUEST_VAR)
    set(INITIAL_REQUEST ${${INITIAL_REQUEST_VAR}})
    _mmsg("Initial request to _get_topo_sort_with_deps() is ${INITIAL_REQUEST}")
    _mmsg("||.UName||_AVAILABLE_COMPONENTS=${||.UName||_AVAILABLE_COMPONENTS}")

    foreach(COMP IN LISTS ||.UName||_AVAILABLE_COMPONENTS)
        set(||.UName||_COMPONENT_DEPS_CURR ${||.UName||_COMPONENT_DEPS_${COMP}})
        foreach(DEP IN LISTS ||.UName||_COMPONENT_DEPS_CURR)
            list(APPEND ||.UName||_COMPONENT_OUTGOING_${DEP} ${COMP})
        endforeach()
    endforeach()

    # Get component dependency set
    set(||.UName||_REQUESTED_COMPONENTS)
    list(LENGTH INITIAL_REQUEST INIT_REQ_LEN)
    if(INIT_REQ_LEN GREATER 0)
        set(REQUEST_QUEUE ${INITIAL_REQUEST})
        list(LENGTH REQUEST_QUEUE RLEN)
        while(RLEN GREATER 0)
            list(POP_FRONT REQUEST_QUEUE COMP)
            list(APPEND ||.UName||_REQUESTED_COMPONENTS ${COMP})
            set(||.UName||_COMPONENT_DEPS_CURR ${||.UName||_COMPONENT_DEPS_${COMP}})
            foreach(DEP IN LISTS ||.UName||_COMPONENT_DEPS_CURR)
                list(APPEND REQUEST_QUEUE ${DEP})
            endforeach()
            list(LENGTH REQUEST_QUEUE RLEN)
        endwhile()
        list(REMOVE_DUPLICATES ||.UName||_REQUESTED_COMPONENTS)
    else()
        set(||.UName||_REQUESTED_COMPONENTS ${||.UName||_AVAILABLE_COMPONENTS})
    endif()
    list(LENGTH ||.UName||_REQUESTED_COMPONENTS REQUESTED_LENGTH)

    # Perform topological sort
    set(||.UName||_COMP_QUEUE)
    foreach(COMP IN LISTS ||.UName||_AVAILABLE_COMPONENTS)
        set(IND ${||.UName||_COMPONENTS_DEPS_IND_${COMP}})
        if(IND EQUAL 0)
            list(APPEND ||.UName||_COMP_QUEUE ${COMP})
        endif()
    endforeach()
    list(LENGTH ||.UName||_COMP_QUEUE QLEN)

    set(||.UName||_TOPO_SORT)
    while(QLEN GREATER 0)
        list(POP_FRONT ||.UName||_COMP_QUEUE COMP)
        if(COMP IN_LIST ||.UName||_REQUESTED_COMPONENTS)
            list(APPEND ||.UName||_TOPO_SORT ${COMP})
        endif()
        set(||.UName||_COMPONENT_OUTGOING_CURR ${||.UName||_COMPONENT_OUTGOING_${COMP}})
        foreach(DEP IN LISTS ||.UName||_COMPONENT_OUTGOING_CURR)
            math(EXPR ||.UName||_COMPONENTS_DEPS_IND_${DEP} "${||.UName||_COMPONENTS_DEPS_IND_${DEP}} - 1")
            if(||.UName||_COMPONENTS_DEPS_IND_${DEP} EQUAL 0)
                list(APPEND ||.UName||_COMP_QUEUE ${DEP})
            endif()
        endforeach()
        list(LENGTH ||.UName||_COMP_QUEUE QLEN)
    endwhile()
    list(LENGTH ||.UName||_TOPO_SORT TLEN)

    if(NOT TLEN EQUAL REQUESTED_LENGTH)
        message(FATAL_ERROR "[||.UName||] Failed to generate topological sort of dependencies from ||.Name||")
    endif()
    _mmsg("Final order: ${||.UName||_TOPO_SORT}")

    set(${OUT_VAR} ${||.UName||_TOPO_SORT} PARENT_SCOPE)
endfunction()